# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160613_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='usr_email',
        ),
    ]
