# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_userinfo_usr_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usr_boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserInfo'),
        ),
    ]
