# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_phone', models.CharField(max_length=50)),
                ('usr_email', models.EmailField(max_length=254)),
                ('usr_active', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactivo')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usr_boss_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserInfo')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('usp_id', models.AutoField(primary_key=True, serialize=False)),
                ('usp_description', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usr_usp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.UserProfile'),
        ),
    ]
