# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usr_active',
            field=models.CharField(choices=[('Y', 'Activo'), ('N', 'Inactivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='usp_description',
            field=models.CharField(choices=[('DRIVER', 'Conductor de un camion'), ('ADMIN', 'Administrador de un grupo de camiones')], max_length=6),
        ),
    ]
